[tool.poetry]
name = "fire-tool-streamlit"
version = "1.0.0"
description = "A Streamlit application for analyzing satellite fire data from NASA FIRMS"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "app"}]

[tool.poetry.dependencies]
streamlit = "^1.26.0"
pandas = "^2.0.0"
numpy = "^1.24.0"
matplotlib = "^3.7.0"
folium = "^0.14.0"
requests = "^2.31.0"
scikit-learn = "^1.3.0"
altair = "^5.0.0"
pillow = "^10.0.0"
geopy = "^2.3.0"
hdbscan = "^0.8.29"
geopandas = {version = "^0.13.0", optional = true}
shapely = {version = "^2.0.0", optional = true}

[tool.poetry.extras]
geo = ["geopandas", "shapely"]

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
pylint = "^2.17.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
fire-tool = "app.main:main"

[tool.black]
line-length = 100
target-version = ["py38"]

[tool.pylint.messages_control]
disable = [
    "C0103",  # Variable name doesn't conform to snake_case naming style
    "C0111",  # Missing docstring
    "C0330",  # Wrong hanging indentation
    "C0326",  # Bad whitespace
    "W0703",  # Catching too general exception
    "R0903",  # Too few public methods
    "R0913",  # Too many arguments
    "R0914",  # Too many local variables
]

[tool.mypy]
python_version = "3.8"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = false